name: ChatEx
main: de.JeterLP.ChatManager.ChatManager
version: 1.0.0
author: TheJeterLP
description: Chat management plugin
softdepend: [PermissionsEx,bpermissions,GroupManager,Vault,AdminCmd,Factions]
